### ISSUE TITLE
communication fails on SROS version 21.2.R1

### ISSUE THREAD

**Issue by baijuw** [nokia/ansible-networking-collections#15]
I am unable to get the connection going with the combination I have at hand of ansible and SROS versions. This was a playbook I have used in the past successfully. Apart from this I have tried to read status from the switch using other playbooks as well. But the error seems to be consistant with all of them. i.e. "[Errno -2] Name or service not known".  
Wanted to check what service I am missing here..
The full error is as follows:-
```
[root@ansible ~]# ansible-playbook sros.play -vvv
ansible-playbook 2.10.9
  config file = /root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /root/ansible.cfg as config file
host_list declined parsing /root/host as it did not pass its verify_file() method
script declined parsing /root/host as it did not pass its verify_file() method
auto declined parsing /root/host as it did not pass its verify_file() method
Parsed /root/host inventory source with ini plugin
redirecting (type: action) ansible.builtin.cli_config to ansible.netcommon.cli_config
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: sros.play **************************************************************************************************************************************************************************************************************************************************************************
1 plays in sros.play

PLAY [Updating configs for L5 on R1 and R2] **************************************************************************************************************************************************************************************************************************************************
META: ran handlers
redirecting (type: action) ansible.builtin.cli_config to ansible.netcommon.cli_config

TASK [Show config] ***************************************************************************************************************************************************************************************************************************************************************************
task path: /root/sros.play:9
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: action) ansible.builtin.cli_config to ansible.netcommon.cli_config
redirecting (type: action) ansible.builtin.cli_config to ansible.netcommon.cli_config
<clab-DigitalEdgePOC-R1> ESTABLISH LOCAL CONNECTION FOR USER: root
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-1426j79fmgkz `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582 `" && echo ansible-tmp-1621237908.0852578-1432-248476235741582="` echo /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.cli_config to ansible.netcommon.cli_config
<clab-DigitalEdgePOC-R1> Attempting python interpreter discovery
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ansible/netcommon/plugins/modules/cli_config.py
<clab-DigitalEdgePOC-R1> PUT /root/.ansible/tmp/ansible-local-1426j79fmgkz/tmprim8b63t TO /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/ /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py && sleep 0'
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py && sleep 0'
<clab-DigitalEdgePOC-R1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.cli_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_config.py", line 475, in <module>
  File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_config.py", line 428, in main
  File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
ansible.module_utils.connection.ConnectionError: [Errno -2] Name or service not known
[DEPRECATION WARNING]: Distribution centos 8.3.2011 on host clab-DigitalEdgePOC-R1 should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform
python for this host. See https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [clab-DigitalEdgePOC-R1]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-1426j79fmgkz/ansible-tmp-1621237908.0852578-1432-248476235741582/AnsiballZ_cli_config.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.cli_config', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_config.py", line 475, in <module>
      File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_config.py", line 428, in main
      File "/tmp/ansible_cli_config_payload_yn5j4sju/ansible_cli_config_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    ansible.module_utils.connection.ConnectionError: [Errno -2] Name or service not known
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************
clab-DigitalEdgePOC-R1     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

Here is the setup:-
```
SROS version:-

A:R1# show version
TiMOS-B-21.2.R1 both/x86_64 Nokia 7750 SR Copyright (c) 2000-2021 Nokia.



Playbook:-

[root@ansible ~]# cat sros.play
---
- name: Updating configs for L5 on R1 and R2
  hosts: R1
  gather_facts: no
  connection: network_cli
  collections:
  - nokia.sros
  tasks:
   - name: Show config
     cli_config:
        config: |
           configure router "Base" bgp
            neighbor "3.3.3.5"
            admin-state enable
            group "IBGP-EVPN-RR"
            exit all



Host file  :-

[sros]
R1
[sros:vars]
ansible_network_os=nokia.sros.md
ansible_user=admin
ansible_password=admin
ANSIBLE_ACTION_WARNINGS=False
```

**Comment by wisotzky** [comment]
Hi @baijuw,
could you please confirm, that the issue is related to SR OS 21.2? Does your setup work successfully against SR OS 20.x? If this is the case, I would assume it may be related to updated SSHv2 ciphers/algo.
/wiso

**Comment by baijuw** [comment]
Hi @wisotzky ,
                 I think the last image I worked with was 20.10.R3. But I cannot be certain as I dont have that setup anymore. 

Thanks
Baiju

**Comment by wisotzky** [comment]
Hi @baijuw,
Not sure about your programming skills... But might be good, if you can validate, if paramiko (python library) has issues to connect to you node already. If this is the case, you may want to consider to update to a later Paramiko version.
/wiso

**Comment by baijuw** [comment]
I can manage that. Will try and let you know.

**Comment by hellt** [comment]
@baijuw 
you refer to your router as `R1` in the playbook
Can you resolve `R1` to an IP address to reach the node, since you don't have `ansible_ssh` or any other address in your hosts file?

**Comment by baijuw** [comment]
@hellt Ansible is running on a containerlab and so is R1. Therefor all names are resolvable.

**Comment by baijuw** [comment]
@hellt wait a minute. You have stumbled upon something. I can ping okay. but ssh has issue with name resolution 

```
[root@ansible ~]# ping R1
PING R1(R1.clab (2001:172:20:20::9)) 56 data bytes
64 bytes from R1.clab (2001:172:20:20::9): icmp_seq=1 ttl=64 time=0.176 ms
64 bytes from R1.clab (2001:172:20:20::9): icmp_seq=2 ttl=64 time=0.204 ms
64 bytes from R1.clab (2001:172:20:20::9): icmp_seq=3 ttl=64 time=0.208 ms
^C
--- R1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.176/0.196/0.208/0.014 ms

[root@ansible ~]# ssh R1
ssh: Could not resolve hostname R1: Name or service not known
```

Therefor @wisotzky I guess paramiko fails too 
```
>>> import paramiko
>>> host = "R1"
>>> port = 22
>>> username = "admin"
>>> password = "admin"
>>> command = "show system information"
>>> ssh = paramiko.SSHClient()
>>> ssh.connect(host, port, username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python3.6/site-packages/paramiko/util.py", line 283, in retry_on_signal
    return function()
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
PermissionError: [Errno 13] Permission denied
```

**Comment by baijuw** [comment]
It works on updating the host file with ansible_host.

**Comment by baijuw** [comment]
What I dont get is that this was working okay earlier without ansible_host earlier. Guess somethings changed in the way ssh resolves names.

**Comment by baijuw** [comment]
Closing issue as it was a problem with name resolution on the ansible host.
