### ISSUE TITLE
ansible 2.10 No module named 'ansible.module_utils.network'

### ISSUE THREAD

**Issue by cwiech** [nokia/ansible-networking-collections#9]
I am upgrading to ansible 2.10 and the noakia.sros module is failing when trying to execute a command on a device (it works fine with 2.9 and versions 1.5.0 of the collection). I don't see any module dependencies listed that I need to install... seems to be something different with 2.10 perhaps.

```
vagrant@ubuntu-bionic:/usr/local$ ansible --version
ansible 2.10.2
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]

vagrant@ubuntu-bionic:/usr/local$ more ~/.ansible/collections/ansible_collections/nokia/sros/MANIFEST.json 
{
 "collection_info": {
  "namespace": "nokia",
  "name": "sros",
  "version": "1.5.0",
```

```
- hosts: nokiavalidator5
  gather_facts: no
  connection: network_cli
  vars:
       ansible_network_os: nokia.sros.classic
  collections:
  - nokia.sros
  tasks:


  - name: sros command load the config old school
    cli_command:
      command: "{{ item }}"
    with_items:
      - "exec safeconfig"
    register: outputregister
```

```
TASK [sros command load the config old school] ****************************************************************************
task path: /home/vagrant/git/ansible-verifier/testconfigs.yml:1062
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 124, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 357, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 613, in _execute
    self._connection = self._get_connection(cvars, templar)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 913, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 826, in get_with_context
    obj.__init__(instance, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 354, in __init__
    self.cliconf = cliconf_loader.get(self._network_os, self)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 780, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 800, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 764, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vagrant/.ansible/collections/ansible_collections/nokia/sros/plugins/cliconf/classic.py", line 25, in <module>
    from ansible.module_utils.network.common.utils import to_list
ModuleNotFoundError: No module named 'ansible.module_utils.network'
fatal: [nokiavalidator5]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by wisotzky** [comment]
Fix added in version 1.6.0 of the SR OS plugin.
Changes available on both GitHub and Ansible Galaxy.

If upgrading from Ansible 2.9 to 2.10 make sure to completely uninstall Ansible running `pip3 uninstall ansible` and then do a fresh install running `pip3 install ansible`. Make sure, to install the ansible.netcommon collection to make this work.

In my setup, some additional cleanup was required. Better option might be, to use virtual environments with python.
